### ISSUE TITLE
options are not modifiable?

### ISSUE THREAD

**Issue by epnev** [drrelyea/SPGL1_python_port#1]
Hi,
Thanks a lot for porting the SPGL1 package in python. I started playing with it, and it appears to me that when spgl1 is called, the user defined options are always overwritten by the default options. I'm copying lines 214-235 of spgl1.py below. In the last line, options are always set to defaultopts. Is it possible to fix that?
Thanks!

```
defaultopts = spgSetParms({
'fid'        :      1 , # File ID for output
'verbosity'  :      2 , # Verbosity level
'iterations' :   10*m , # Max number of iterrations
'nPrevVals'  :      3 , # Number previous func values for linesearch
'bpTol'      :  1e-06 , # Tolerance for basis pursuit solution
'lsTol'      :  1e-06 , # Least-squares optimality tolerance
'optTol'     :  1e-04 , # Optimality tolerance
'decTol'     :  1e-04 , # Reqd rel. change in primal obj. for Newton
'stepMin'    :  1e-16 , # Minimum spectral step
'stepMax'    :  1e+05 , # Maximum spectral step
'rootMethod' :      2 , # Root finding method: 2=quad,1=linear (not used).
'activeSetIt':    np.inf , # Exit with EXIT_ACTIVE_SET if nnz same for # its.
'subspaceMin':      0 , # Use subspace minimization
'iscomplex'  :    np.nan , # Flag set to indicate complex problem
'maxMatvec'  :    np.inf , # Maximum matrix-vector multiplies allowed
'weights'    :      1 , # Weights W in ||Wx||_1
'project'    : NormL1_project ,
'primal_norm': NormL1_primal  ,
'dual_norm'  : NormL1_dual
   })
options = spgSetParms(defaultopts);
```

**Comment by mrava87** [comment]
Hi,
I noticed the same in the version you tried. Things have changed quite a lot in this project in the last couple of weeks and now we do  not handle optional parameters in this way anymore, but we use proper python way of handling optional input parameters to functions.

Would you mind giving it a try again with the new version once the pull request https://github.com/drrelyea/SPGL1_python_port/pull/17 is accepted and let me know if things work as you would like now?

**Comment by mrava87** [comment]
@drrelyea I think this is fixed and we haven’t got any reply, can you please close it
