### ISSUE TITLE
future plans

### ISSUE THREAD

**Issue by mrava87** [drrelyea/SPGL1_python_port#14]
Hello,
I am the main developer and mantainer of https://github.com/Statoil/pylops. We will be interest to use sparse solvers for some of our inverse problems and in the past I successfully used SPGL1 in Matlab. I am happy to see that you started porting it to python and would like to ask some questions. 

How active is this project? Are you planning to do some more work, e.g:
- add unittest/pytest
- make proper numpydoc style code docstrings
- avoid using your internal lsqr but use ‘official’ scipy one
- add to pypi (but this may not be needed, read below)

Reason I ask these questions is that I discussed with scipy developers about having more solvers in their suite and they say they are happy to consider including any solver provided that:
- code is to their standards (style, tests, docstring)
- license adheres to their licence policy (https://docs.scipy.org/doc/scipy/reference/hacking.html)

Please let me know how you feel about this. I can of course contribute and help out getting things in place but as I say I’d be more happy to do it if we agree that this will eventually migrate into scipy instead of being a standalone library :)

PS: if you think this is a good way we will also need to check with the Matlab developers of SPGL1 (since you ported their code) to either change their licence or grant permission to scipy to use a less restrictive one for the scipy version.

**Comment by drrelyea** [comment]
Hi Matteo,

I had originally coded this for personal use. I'd intended to fix it up and
port it over to scipy, as it definitely makes more sense for it to be there
as opposed to standalone, but I ended up pursuing other efforts. There's no
active development on the project.

I'd be happy to hand it over (or just tacitly accept pushes) if you'd like
to get the code up to scipy standards. There are two other people who've
provided updates, and one expressed interest in making the library a lot
more efficient, but I haven't heard from either of them in months. I don't
think either is particularly serious, fwiw.

And yes, you'd definitely have to speak the original Matlab devs.

**Comment by mrava87** [comment]
Thanks for quick feedback! 

Let me just get in touch with the MATLAB guys and see what they think. If they agree, I think we can keep pushing to your repo if it’s ok for you until things are to scipy level and the try to embed it there and go for pull request :) 

Hopefully the other guys that provided updates see this and comment, I am happy to help but don’t need to be the only one working on repo ;) 

Will keep you posted here so things are easy for everyone to follow

**Comment by Jwink3101** [comment]
I think I am one of those who expressed some interest. I am still interested, but I do not think I have the time to devote to getting this up to SciPy calibre. (especially since I can't officially work on it at work and I have a new baby at home).

With that said, I will keep following and if time permits, I will happily jump in! And I would really love to see this method (or another reliable sparse solver) in SciPy.

You may also find interest in sklearn if SciPy doesn't make sense.

**Comment by mrava87** [comment]
Thanks for quick reply. I agree sklearn could be another good alternative :)

Myself and a few colleagues in academia may team up and start pushing code here at some point, you are welcome to jump in!

**Comment by mrava87** [comment]
Hi, 
took some time but we spoke to the creators of SPGL1 and they are happy to have a different licence for the python version to facilitate inclusion in SciPy. I forked your repo and started working on some clean up. Let me know if you prefer me to pull request every time I have some milestone or keep working off the fork. 

In case you are happy with pull requests i would suggest making a tag for current version so that you can easily go back to where you left things as I will make non-compatible changes trying to give script flavour to the solver before getting in touch with Scipy people again :)

**Comment by drrelyea** [comment]
I haven't used this in four years, so feel free to keep making requests.
I'll make sure the code runs and then approve.

**Comment by mrava87** [comment]
Sounds good :) I have taken your spglexample and made into tests, once they all pass with the new code I will make a request. I can add a travis file so you don’t need to check manually yourself if that helps?

**Comment by drrelyea** [comment]
Great - thank you.
