### ISSUE TITLE
data type changed from float32 to float64 inside spgl1

### ISSUE THREAD

**Issue by galveston12345** [drrelyea/SPGL1_python_port#26]
Hi, 

I tried to use spgl1 with an operator that operates on float32 array (b, x0 are float32 arrays). However, it appears inside spgl1.py '_oneprojector_i' and '_oneprojector_d' alter the data type to float64 by calling 'x=np.zeros(n)'. My bypass is to change it to 'x=np.zeros(n, dtype=b.dtype)'. If there is anything I'm missing, I'm glad to hear. Thanks.

**Comment by mrava87** [comment]
Hi,
Thanks for noticing this. Indeed to your bypass is correct. Do you want to make a PR?

**Comment by galveston12345** [comment]
yeah, will do. Thanks for the confirmation.

**Comment by mrava87** [comment]
It would be great to add also some new tests to verify that the new code works as expected, i.e. when inputs of `float32` go into these functions outputs of the same type come out :)

I worry the problem may be in other parts of the code (anytime a `np.zeros` appears) as I never really stress test it with smaller than `float64`, but perhaps it is the only place as I seem to understand that by simply changing to `x=np.zeros(n, dtype=b.dtype)` these two routines, the output of spgl1 stays `float32`?

**Comment by galveston12345** [comment]
These two routines stand out when I look at the memory profile. And it seems the arrays created from them are more persistent than others (garbage collected by python). There might be one more obvious place that needs the change as well in 'spgl1.py'. It's a bit hard to be 100% affirmative 

> 1175                     if istop != 4:
> 1176                         # Push dx back into full space: dx = Z dx.
> 1177                         dx = np.zeros(n)

**Comment by mrava87** [comment]
Yes, that one needs changed. I am looking at it now and it seems that with a couple of changes spgl1 can work with both `float32` and any complex returning the correct type (no implicit upcasting). I am going to make a PR adding also some tests to make sure if any change is made to the codebase in future we don't break this behaviour, would be good if you can take a look :)

**Comment by galveston12345** [comment]
happy to do so :)

**Comment by drrelyea** [comment]
This looks like it was addressed appropriately. @galveston12345, will you be looking at the change?

**Comment by mrava87** [comment]
It's also now available on PYPI (version 0.0.2)

Thanks a lot again for spotting this, and please report back if you still experience any automatic type change. Hopefully it is not going to happen anymore as all the new tests check that type out is consistent to type in but there may be some behaviours that we haven't stress tested yet :)

**Comment by mrava87** [comment]
I think we can close this @drrelyea
