### ISSUE TITLE
spgl1() got multiple values for argument 'x0'

### ISSUE THREAD

**Issue by GillesC** [drrelyea/SPGL1_python_port#29]
you provide both x0 separately and through **kwargs to the spfl1 function:
```python
x0 = None
x, r, g, info = spgl1(A, b, tau, sigma, x0, **kwargs)
```
at [this line](https://github.com/drrelyea/spgl1/blob/master/spgl1/spgl1.py#L1398).

You could discard the `x0 = None` is this is by default None in spgl1() and the same applies for `tau`.

**Comment by mrava87** [comment]
Hi @GillesC,
thanks!

I think you are right, the ``x0=None`` is redundant as this is already the default behavior of `spgl1` so if you don't provide it, it will work the same way. And of course if you provide it in `kwargs` it will overwrite as it comes after. 

You want to make a PR and remove  ``x0=None`` in this and also spg_lassom spg_bp, and spg_bpdn?

**Comment by GillesC** [comment]
Done :) Thank you for library!
